/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-08-29 at 02:08:19 UTC 
 * Modify at your own risk.
 */

package com.hikefinderapp.entity.hikeendpoint;

/**
 * Service definition for Hikeendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link HikeendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Hikeendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the hikeendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://seraphic-bliss-641.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "hikeendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Hikeendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Hikeendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getHike".
   *
   * This request holds the parameters needed by the hikeendpoint server.  After setting any optional
   * parameters, call the {@link GetHike#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetHike getHike(java.lang.Long id) throws java.io.IOException {
    GetHike result = new GetHike(id);
    initialize(result);
    return result;
  }

  public class GetHike extends HikeendpointRequest<com.hikefinderapp.entity.hikeendpoint.model.Hike> {

    private static final String REST_PATH = "hike/{id}";

    /**
     * Create a request for the method "getHike".
     *
     * This request holds the parameters needed by the the hikeendpoint server.  After setting any
     * optional parameters, call the {@link GetHike#execute()} method to invoke the remote operation.
     * <p> {@link
     * GetHike#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetHike(java.lang.Long id) {
      super(Hikeendpoint.this, "GET", REST_PATH, null, com.hikefinderapp.entity.hikeendpoint.model.Hike.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetHike setAlt(java.lang.String alt) {
      return (GetHike) super.setAlt(alt);
    }

    @Override
    public GetHike setFields(java.lang.String fields) {
      return (GetHike) super.setFields(fields);
    }

    @Override
    public GetHike setKey(java.lang.String key) {
      return (GetHike) super.setKey(key);
    }

    @Override
    public GetHike setOauthToken(java.lang.String oauthToken) {
      return (GetHike) super.setOauthToken(oauthToken);
    }

    @Override
    public GetHike setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetHike) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetHike setQuotaUser(java.lang.String quotaUser) {
      return (GetHike) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetHike setUserIp(java.lang.String userIp) {
      return (GetHike) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetHike setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetHike set(String parameterName, Object value) {
      return (GetHike) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertHike".
   *
   * This request holds the parameters needed by the hikeendpoint server.  After setting any optional
   * parameters, call the {@link InsertHike#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.hikefinderapp.entity.hikeendpoint.model.Hike}
   * @return the request
   */
  public InsertHike insertHike(com.hikefinderapp.entity.hikeendpoint.model.Hike content) throws java.io.IOException {
    InsertHike result = new InsertHike(content);
    initialize(result);
    return result;
  }

  public class InsertHike extends HikeendpointRequest<com.hikefinderapp.entity.hikeendpoint.model.Hike> {

    private static final String REST_PATH = "hike";

    /**
     * Create a request for the method "insertHike".
     *
     * This request holds the parameters needed by the the hikeendpoint server.  After setting any
     * optional parameters, call the {@link InsertHike#execute()} method to invoke the remote
     * operation. <p> {@link
     * InsertHike#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.hikefinderapp.entity.hikeendpoint.model.Hike}
     * @since 1.13
     */
    protected InsertHike(com.hikefinderapp.entity.hikeendpoint.model.Hike content) {
      super(Hikeendpoint.this, "POST", REST_PATH, content, com.hikefinderapp.entity.hikeendpoint.model.Hike.class);
    }

    @Override
    public InsertHike setAlt(java.lang.String alt) {
      return (InsertHike) super.setAlt(alt);
    }

    @Override
    public InsertHike setFields(java.lang.String fields) {
      return (InsertHike) super.setFields(fields);
    }

    @Override
    public InsertHike setKey(java.lang.String key) {
      return (InsertHike) super.setKey(key);
    }

    @Override
    public InsertHike setOauthToken(java.lang.String oauthToken) {
      return (InsertHike) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertHike setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertHike) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertHike setQuotaUser(java.lang.String quotaUser) {
      return (InsertHike) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertHike setUserIp(java.lang.String userIp) {
      return (InsertHike) super.setUserIp(userIp);
    }

    @Override
    public InsertHike set(String parameterName, Object value) {
      return (InsertHike) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listHike".
   *
   * This request holds the parameters needed by the hikeendpoint server.  After setting any optional
   * parameters, call the {@link ListHike#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public ListHike listHike() throws java.io.IOException {
    ListHike result = new ListHike();
    initialize(result);
    return result;
  }

  public class ListHike extends HikeendpointRequest<com.hikefinderapp.entity.hikeendpoint.model.CollectionResponseHike> {

    private static final String REST_PATH = "hike";

    /**
     * Create a request for the method "listHike".
     *
     * This request holds the parameters needed by the the hikeendpoint server.  After setting any
     * optional parameters, call the {@link ListHike#execute()} method to invoke the remote operation.
     * <p> {@link
     * ListHike#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListHike() {
      super(Hikeendpoint.this, "GET", REST_PATH, null, com.hikefinderapp.entity.hikeendpoint.model.CollectionResponseHike.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListHike setAlt(java.lang.String alt) {
      return (ListHike) super.setAlt(alt);
    }

    @Override
    public ListHike setFields(java.lang.String fields) {
      return (ListHike) super.setFields(fields);
    }

    @Override
    public ListHike setKey(java.lang.String key) {
      return (ListHike) super.setKey(key);
    }

    @Override
    public ListHike setOauthToken(java.lang.String oauthToken) {
      return (ListHike) super.setOauthToken(oauthToken);
    }

    @Override
    public ListHike setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListHike) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListHike setQuotaUser(java.lang.String quotaUser) {
      return (ListHike) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListHike setUserIp(java.lang.String userIp) {
      return (ListHike) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListHike setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String queryString;

    /**

     */
    public java.lang.String getQueryString() {
      return queryString;
    }

    public ListHike setQueryString(java.lang.String queryString) {
      this.queryString = queryString;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListHike setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListHike set(String parameterName, Object value) {
      return (ListHike) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeHike".
   *
   * This request holds the parameters needed by the hikeendpoint server.  After setting any optional
   * parameters, call the {@link RemoveHike#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public RemoveHike removeHike(java.lang.Long id) throws java.io.IOException {
    RemoveHike result = new RemoveHike(id);
    initialize(result);
    return result;
  }

  public class RemoveHike extends HikeendpointRequest<Void> {

    private static final String REST_PATH = "hike/{id}";

    /**
     * Create a request for the method "removeHike".
     *
     * This request holds the parameters needed by the the hikeendpoint server.  After setting any
     * optional parameters, call the {@link RemoveHike#execute()} method to invoke the remote
     * operation. <p> {@link
     * RemoveHike#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveHike(java.lang.Long id) {
      super(Hikeendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveHike setAlt(java.lang.String alt) {
      return (RemoveHike) super.setAlt(alt);
    }

    @Override
    public RemoveHike setFields(java.lang.String fields) {
      return (RemoveHike) super.setFields(fields);
    }

    @Override
    public RemoveHike setKey(java.lang.String key) {
      return (RemoveHike) super.setKey(key);
    }

    @Override
    public RemoveHike setOauthToken(java.lang.String oauthToken) {
      return (RemoveHike) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveHike setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveHike) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveHike setQuotaUser(java.lang.String quotaUser) {
      return (RemoveHike) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveHike setUserIp(java.lang.String userIp) {
      return (RemoveHike) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveHike setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveHike set(String parameterName, Object value) {
      return (RemoveHike) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateHike".
   *
   * This request holds the parameters needed by the hikeendpoint server.  After setting any optional
   * parameters, call the {@link UpdateHike#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.hikefinderapp.entity.hikeendpoint.model.Hike}
   * @return the request
   */
  public UpdateHike updateHike(com.hikefinderapp.entity.hikeendpoint.model.Hike content) throws java.io.IOException {
    UpdateHike result = new UpdateHike(content);
    initialize(result);
    return result;
  }

  public class UpdateHike extends HikeendpointRequest<com.hikefinderapp.entity.hikeendpoint.model.Hike> {

    private static final String REST_PATH = "hike";

    /**
     * Create a request for the method "updateHike".
     *
     * This request holds the parameters needed by the the hikeendpoint server.  After setting any
     * optional parameters, call the {@link UpdateHike#execute()} method to invoke the remote
     * operation. <p> {@link
     * UpdateHike#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.hikefinderapp.entity.hikeendpoint.model.Hike}
     * @since 1.13
     */
    protected UpdateHike(com.hikefinderapp.entity.hikeendpoint.model.Hike content) {
      super(Hikeendpoint.this, "PUT", REST_PATH, content, com.hikefinderapp.entity.hikeendpoint.model.Hike.class);
    }

    @Override
    public UpdateHike setAlt(java.lang.String alt) {
      return (UpdateHike) super.setAlt(alt);
    }

    @Override
    public UpdateHike setFields(java.lang.String fields) {
      return (UpdateHike) super.setFields(fields);
    }

    @Override
    public UpdateHike setKey(java.lang.String key) {
      return (UpdateHike) super.setKey(key);
    }

    @Override
    public UpdateHike setOauthToken(java.lang.String oauthToken) {
      return (UpdateHike) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateHike setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateHike) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateHike setQuotaUser(java.lang.String quotaUser) {
      return (UpdateHike) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateHike setUserIp(java.lang.String userIp) {
      return (UpdateHike) super.setUserIp(userIp);
    }

    @Override
    public UpdateHike set(String parameterName, Object value) {
      return (UpdateHike) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Hikeendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Hikeendpoint}. */
    @Override
    public Hikeendpoint build() {
      return new Hikeendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link HikeendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setHikeendpointRequestInitializer(
        HikeendpointRequestInitializer hikeendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(hikeendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
